# config context path to "/" by setting an empty string
server:
  contextPath:


# JACKSON, JPA
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: update